# action.yml
name: 'K8AppDeploy'
description: 'Deploy Docker App to Kubernetes Cluster using ingress'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kube-config }}
    - ${{ inputs.container-image }}
    - ${{ inputs.app-name }}
    - ${{ inputs.app-namespace }}
    - ${{ inputs.app-port }}
    - ${{ inputs.ingress-hostname }}
    - ${{ inputs.ingress-path }}
    - ${{ inputs.ingress-extra-annotations }}
    - ${{ inputs.ingress-use-cache }}
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  kube-config:
    description: 'kube config data. Generate it loaclly using: (cat $HOME/.kube/config | base64)'
    required: true
  container-image:
    description: 'The container image to pull in kubernetes. Can use private registry for example repo.example.com/nginix:latest'
    required: true
  app-name:
    description: 'Name to be used for kubernetes resources: service, deploy, pod, ingress'
    required: true
  app-namespace:
    description: 'Namespace to be used generated and used for kubernetes resources: service, deploy, pod, ingress'
    default: default
  app-port:
    description: 'Container port exposed by image to use as source for ingress reverse proxy'
    required: true
  ingress-hostname:
    description: 'Ingress host. For example app.mydomain.com'
    required: true
  ingress-path:
    description: 'Ingress path used for backend and frontend. See kubernetes documentation'
    default: /
  ingress-extra-annotations:
    description: 'Additional annotations for the ingress. String separated by coma. (For Example:) mykey1: value1, mykey2: value2'
  ingress-use-cache:
    description: 'Enables nginx-ingress cache system. Accepted values: false (default), true'
    default: false
