on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy to Kubernetes cluster minimal
      uses: josuelopezv/K8AppDeploy@main
      with:
        kube-config: ${{ secrets.KUBE_CONFIG_DATA}}
        container-image: nginx:latest
        app-name: my-app
        ingress-hostname: example.agileliteracy.com
        app-port: 80

    - name: Deploy to Kubernetes cluster full
      uses: josuelopezv/K8AppDeploy@main
      with:
        kube-config: ${{ secrets.KUBE_CONFIG_DATA}}
        container-image: nginx:latest
        app-name: my-app
        app-namespace: app-example
        ingress-hostname: example.agileliteracy.com
        app-port: 80
        ingress-extra-annotations: |
          nginx.ingress.kubernetes.io/proxy-buffering: "on",
          nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
        extra-cmd: |
          kubectl get pods -A
          echo "completed"
